providers:
  docker:
    swarmMode: true
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false

entryPoints:
  web:
   address: ":80"
  secureweb:
   address: ":443"

api:
  dashboard: true
  insecure: true

log:
  level: DEBUG
