---
- name: Update packages
  import_tasks: package_repo.yml

- name: Install docker.io package
  become: true
  apt:
    name: docker.io
    state: present

- name: Start docker service
  become: true
  service:
    name: docker.service
    state: started
