---
- name: Check swarm worker status
  become: true
  shell: docker info | grep 'Swarm:' | awk '{print $2}'
  register: worker_swarm_status
  changed_when: "'inactive' in worker_swarm_status"

- name: Load swarm worker token
  when: worker_swarm_status.stdout == 'inactive'
  local_action: shell cat ./worker_token
  register: worker_token

- name: Load swarm manager ip
  when: worker_swarm_status.stdout == 'inactive'
  local_action: shell cat ./manager_ip
  register: swarm_manager_ip

- name: Join swarm as worker
  become: true
  when: worker_swarm_status.stdout == 'inactive'
  shell: docker swarm join --advertise-addr {{ ansible_facts.ens3.ipv4.address }} --listen-addr {{ ansible_facts.ens3.ipv4.address }}:{{ swarm_managment_port }} --token {{ worker_token.stdout }} {{ swarm_manager_ip.stdout }}:{{ swarm_managment_port }}

