---
- name: Check primary manager swarm status
  become: true
  run_once: true
  shell: docker info | grep 'Swarm' | awk '{print $2}'
  register: primary_manager_swarm_status
  changed_when: "'inactive' in primary_manager_swarm_status.stdout"

- name: Initialise swarm for primary manager 
  become: true
  shell: docker swarm init --advertise-addr {{ ansible_facts.ens3.ipv4.address }}:{{ swarm_managment_port }}
  run_once: true
  notify: primary manager created
  when: primary_manager_swarm_status.stdout == 'inactive'
