---
- name: check swarm worker status
  become: true
  shell: docker info | grep 'Swarm:' | awk '{print $2}'
  register: swarm_worker_status

- name: Load swarm worker token
  when: swarm_worker_status.stdout == 'inactive'
  local_action: shell cat ./worker_token
  register: swarm_worker_token

- name: Load swarm manager ip
  when: swarm_worker_status.stdout == 'inactive'
  local_action: shell cat ./manager_ip
  register: swarm_worker_manager_ip

- name: join swarm as worker
  become: true
  when: swarm_worker_status.stdout == 'inactive'
  shell: docker swarm join --advertise-addr {{ ansible_facts.ens3.ipv4.address }} --listen-addr {{ ansible_facts.ens3.ipv4.address }}:2377 --token {{swarm_worker_token.stdout }} {{swarm_worker_manager_ip.stdout}}:2377

