---
- name: Check ancillary manager swarm status
  become: true
  shell: docker info | grep 'Swarm' | awk '{print $2}'
  register: ancilary_manager_swarm_status

- name: Load swarm manager ip
  local_action: shell cat ./manager_ip
  register: swarm_manager_ip
  when: ancilary_manager_swarm_status.stdout == 'inactive'

- name: Load swarm manager join token
  local_action: shell cat ./manager_token
  register: swarm_manager_token
  when: ancilary_manager_swarm_status.stdout == 'inactive'

- name: Join swarm as ancillary manager
  become: true
  shell: docker swarm join --advertise-addr {{ ansible_facts.ens3.ipv4.address }} --listen-addr {{ ansible_facts.ens3.ipv4.address }}:2377 --token {{ swarm_manager_token.stdout }} {{ swarm_manager_ip.stdout }}:2377
  when: ancilary_manager_swarm_status.stdout == 'inactive'
