---
- name: Check primary manager swarm status
  become: true
  shell: docker info | grep 'Swarm' | awk '{print $2}'
  register: primary_manager_swarm_status

- name: Initialise swarm for primary manager
  become: true
  shell: docker swarm init --advertise-addr {{ ansible_facts.ens3.ipv4.address }}
  when: primary_manager_swarm_status.stdout == 'inactive'

- name: Store swarm manager ip
  become: false
  local_action: copy content="{{ ansible_facts.ens3.ipv4.address }}" dest="./manager_ip"

- name: Extract swarm manager token
  become: true
  shell: docker swarm join-token manager -q
  register: swarm_manager_token

- name: Store swarm manager join token
  become: false
  local_action: copy content="{{ swarm_manager_token.stdout }}" dest="./manager_token"

- name: Extract swarm worker token
  become: true
  shell: docker swarm join-token worker -q
  register: swarm_worker_token

- name: Store swarm manager join token
  become: false
  local_action: copy content="{{ swarm_worker_token.stdout }}" dest="./worker_token"
