version: '3.6'

services:
  agent:
    image: portainer/agent
    environment:
      AGENT_SECRET: secret_token
      CAP_HOST_MANAGEMENT: 1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
      - /:/host
    networks:
      - switch
    deploy:
      mode: global
      placement:
        constraints: [node.platform.os == linux]
      restart_policy:
        condition: on-failure
        delay: 15s
        max_attempts: 3
        window: 60s

  portainer:
    image: portainer/portainer-ce
    command: -H tcp://tasks.agent:9001 --tlsskipverify
    environment:
      AGENT_SECRET: secret_token
      CAP_HOST_MANAGEMENT: 1
    ports:
      - 9000:9000
    networks:
      - switch
      - proxy_switch
    volumes:
      - portainer_data:/data
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]
      labels:
        - traefik.enable=true
        - traefik.docker.network=proxy_switch
        - traefik.http.routers.portainer.rule=(PathPrefix(`/portainer`))
        - traefik.http.services.portainer.loadbalancer.server.port=9000
      restart_policy:
        condition: on-failure
        delay: 15s
        max_attempts: 3
        window: 60s

networks:
  switch:
    driver: overlay
    attachable: true
  proxy_switch:
    external: true

volumes:
  portainer_data:
