version: '3.6'

services:
  traefik:
    image: traefik:v2.2
    ports:
      - 80:80
      - 8080:8080
      - 443:443
      - 8443:8443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /var/stacks/config/traefik.yml:/etc/traefik/traefik.yml
    networks:
      - switch
    deploy:
      labels:
        - traefik.http.routers.api.service=api@internal
        - traefik.http.routers.api.rule=Host(PathPrefix(`/traefik`))
        # Dummy service for Swarm port detection. The port can be any valid integer value.
        - traefik.http.services.dummy-svc.loadbalancer.server.port=9999
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: on-failure
        delay: 15s
        max_attempts: 3
        window: 60s

networks:
  switch:
    driver: overlay
    attachable: true
