version: '3.6'

services:
  helloworld:
    image: tutum/hello-world:latest
    networks:
      - proxy_switch
    deploy:
      replicas: 5
      labels:
        - traefik.enable=true
        - traefik.docker.network=proxy_switch
        - traefik.http.routers.helloworld.rule=(PathPrefix(`/test`))
        - traefik.http.services.helloworld.loadbalancer.server.port=80

networks:
  proxy_switch:
    external: true
