---
- name: Extract swarm manager token
  become: true
  shell: docker swarm join-token manager -q
  register: swarm_manager_token
  listen: "primary manager created"

- name: Store swarm manager join token
  become: false
  local_action: copy content="{{ swarm_manager_token.stdout }}" dest="./manager_token"
  listen: "primary manager created"

- name: Extract swarm worker token
  become: true
  shell: docker swarm join-token worker -q
  register: swarm_worker_token
  listen: "primary manager created"

- name: Store swarm manager join token
  become: false
  local_action: copy content="{{ swarm_worker_token.stdout }}" dest="./worker_token"
  listen: "primary manager created"

- name: Store swarm manager ip
  become: false
  local_action: copy content="{{ ansible_facts.ens3.ipv4.address }}" dest="./manager_ip"
  listen: "primary manager created"
